# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maeng/codes/venusblast

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maeng/codes/venusblast

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maeng/codes/venusblast/CMakeFiles /home/maeng/codes/venusblast/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maeng/codes/venusblast/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named venusblast

# Build rule for target.
venusblast: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 venusblast
.PHONY : venusblast

# fast build rule for target.
venusblast/fast:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/build
.PHONY : venusblast/fast

src/Application.o: src/Application.cpp.o

.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i

.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s

.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Scene/MenuScene.o: src/Scene/MenuScene.cpp.o

.PHONY : src/Scene/MenuScene.o

# target to build an object file
src/Scene/MenuScene.cpp.o:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Scene/MenuScene.cpp.o
.PHONY : src/Scene/MenuScene.cpp.o

src/Scene/MenuScene.i: src/Scene/MenuScene.cpp.i

.PHONY : src/Scene/MenuScene.i

# target to preprocess a source file
src/Scene/MenuScene.cpp.i:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Scene/MenuScene.cpp.i
.PHONY : src/Scene/MenuScene.cpp.i

src/Scene/MenuScene.s: src/Scene/MenuScene.cpp.s

.PHONY : src/Scene/MenuScene.s

# target to generate assembly for a file
src/Scene/MenuScene.cpp.s:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Scene/MenuScene.cpp.s
.PHONY : src/Scene/MenuScene.cpp.s

src/Scene/TitleScene.o: src/Scene/TitleScene.cpp.o

.PHONY : src/Scene/TitleScene.o

# target to build an object file
src/Scene/TitleScene.cpp.o:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Scene/TitleScene.cpp.o
.PHONY : src/Scene/TitleScene.cpp.o

src/Scene/TitleScene.i: src/Scene/TitleScene.cpp.i

.PHONY : src/Scene/TitleScene.i

# target to preprocess a source file
src/Scene/TitleScene.cpp.i:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Scene/TitleScene.cpp.i
.PHONY : src/Scene/TitleScene.cpp.i

src/Scene/TitleScene.s: src/Scene/TitleScene.cpp.s

.PHONY : src/Scene/TitleScene.s

# target to generate assembly for a file
src/Scene/TitleScene.cpp.s:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/Scene/TitleScene.cpp.s
.PHONY : src/Scene/TitleScene.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/venusblast.dir/build.make CMakeFiles/venusblast.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... venusblast"
	@echo "... edit_cache"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Scene/MenuScene.o"
	@echo "... src/Scene/MenuScene.i"
	@echo "... src/Scene/MenuScene.s"
	@echo "... src/Scene/TitleScene.o"
	@echo "... src/Scene/TitleScene.i"
	@echo "... src/Scene/TitleScene.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

